// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMessage.proto

#ifndef PROTOBUF_PBMessage_2eproto__INCLUDED
#define PROTOBUF_PBMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_PBMessage_2eproto();
void protobuf_AssignDesc_PBMessage_2eproto();
void protobuf_ShutdownFile_PBMessage_2eproto();

class CSLogin;
class SCLoginRet;

// ===================================================================

class CSLogin : public ::google::protobuf::Message {
 public:
  CSLogin();
  virtual ~CSLogin();

  CSLogin(const CSLogin& from);

  inline CSLogin& operator=(const CSLogin& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSLogin& default_instance();

  void Swap(CSLogin* other);

  // implements Message ----------------------------------------------

  inline CSLogin* New() const { return New(NULL); }

  CSLogin* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSLogin& from);
  void MergeFrom(const CSLogin& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CSLogin* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes commandId = 1;
  bool has_commandid() const;
  void clear_commandid();
  static const int kCommandIdFieldNumber = 1;
  const ::std::string& commandid() const;
  void set_commandid(const ::std::string& value);
  void set_commandid(const char* value);
  void set_commandid(const void* value, size_t size);
  ::std::string* mutable_commandid();
  ::std::string* release_commandid();
  void set_allocated_commandid(::std::string* commandid);

  // @@protoc_insertion_point(class_scope:CSLogin)
 private:
  inline void set_has_commandid();
  inline void clear_has_commandid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr commandid_;
  friend void  protobuf_AddDesc_PBMessage_2eproto();
  friend void protobuf_AssignDesc_PBMessage_2eproto();
  friend void protobuf_ShutdownFile_PBMessage_2eproto();

  void InitAsDefaultInstance();
  static CSLogin* default_instance_;
};
// -------------------------------------------------------------------

class SCLoginRet : public ::google::protobuf::Message {
 public:
  SCLoginRet();
  virtual ~SCLoginRet();

  SCLoginRet(const SCLoginRet& from);

  inline SCLoginRet& operator=(const SCLoginRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SCLoginRet& default_instance();

  void Swap(SCLoginRet* other);

  // implements Message ----------------------------------------------

  inline SCLoginRet* New() const { return New(NULL); }

  SCLoginRet* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SCLoginRet& from);
  void MergeFrom(const SCLoginRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SCLoginRet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ret = 1;
  bool has_ret() const;
  void clear_ret();
  static const int kRetFieldNumber = 1;
  ::google::protobuf::int32 ret() const;
  void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SCLoginRet)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ret_;
  friend void  protobuf_AddDesc_PBMessage_2eproto();
  friend void protobuf_AssignDesc_PBMessage_2eproto();
  friend void protobuf_ShutdownFile_PBMessage_2eproto();

  void InitAsDefaultInstance();
  static SCLoginRet* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CSLogin

// required bytes commandId = 1;
inline bool CSLogin::has_commandid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSLogin::set_has_commandid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSLogin::clear_has_commandid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSLogin::clear_commandid() {
  commandid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_commandid();
}
inline const ::std::string& CSLogin::commandid() const {
  // @@protoc_insertion_point(field_get:CSLogin.commandId)
  return commandid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSLogin::set_commandid(const ::std::string& value) {
  set_has_commandid();
  commandid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CSLogin.commandId)
}
inline void CSLogin::set_commandid(const char* value) {
  set_has_commandid();
  commandid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CSLogin.commandId)
}
inline void CSLogin::set_commandid(const void* value, size_t size) {
  set_has_commandid();
  commandid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CSLogin.commandId)
}
inline ::std::string* CSLogin::mutable_commandid() {
  set_has_commandid();
  // @@protoc_insertion_point(field_mutable:CSLogin.commandId)
  return commandid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSLogin::release_commandid() {
  clear_has_commandid();
  return commandid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSLogin::set_allocated_commandid(::std::string* commandid) {
  if (commandid != NULL) {
    set_has_commandid();
  } else {
    clear_has_commandid();
  }
  commandid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), commandid);
  // @@protoc_insertion_point(field_set_allocated:CSLogin.commandId)
}

// -------------------------------------------------------------------

// SCLoginRet

// optional int32 ret = 1;
inline bool SCLoginRet::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SCLoginRet::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SCLoginRet::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SCLoginRet::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 SCLoginRet::ret() const {
  // @@protoc_insertion_point(field_get:SCLoginRet.ret)
  return ret_;
}
inline void SCLoginRet::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:SCLoginRet.ret)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PBMessage_2eproto__INCLUDED
